package com.smartsched.model;

import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;
import org.springframework.data.mongodb.core.mapping.DBRef;

@Document(collection = "groups")
public class Group {
    @Id
    private String groupId; // Auto-generated by MongoDB
    private String groupName;

    @DBRef
    private Course course; // Reference to Course

    // Default constructor
    public Group() {}

    public Group(String groupName, Course course) {
        this.groupName = groupName;
        this.course = course;
    }

    // Getters and Setters
    public String getGroupId() { return groupId; }

    public String getGroupName() { return groupName; }
    public void setGroupName(String groupName) { this.groupName = groupName; }

    public Course getCourse() { return course; }
    public void setCourse(Course course) { this.course = course; }
}
