package com.smartsched.model;

import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;
import org.springframework.data.mongodb.core.mapping.DBRef;

@Document(collection = "modules")
public class Module {
    @Id
    private String moduleId; // Auto-generated by MongoDB
    private String code;
    private String moduleName;
    private String moduleDescription;

    @DBRef
    private Course course; // Reference to Course

    // Default constructor
    public Module() {}

    public Module(String code, String moduleName, String moduleDescription, Course course) {
        this.code = code;
        this.moduleName = moduleName;
        this.moduleDescription = moduleDescription;
        this.course = course;
    }

    // Getters and Setters
    public String getModuleId() { return moduleId; }

    public String getCode() { return code; }
    public void setCode(String code) { this.code = code; }

    public String getModuleName() { return moduleName; }
    public void setModuleName(String moduleName) { this.moduleName = moduleName; }

    public String getModuleDescription() { return moduleDescription; }
    public void setModuleDescription(String moduleDescription) { this.moduleDescription = moduleDescription; }

    public Course getCourse() { return course; }
    public void setCourse(Course course) { this.course = course; }
}